#!/usr/bin/env node
// install.js

const fs = require('fs');
const path = require('path');
const { cwd } = require('process');

const dstPath = path.resolve(cwd(), 'src', 'assets', 'asset--import');
const dstFilePath = path.join(dstPath, '_index.scss');
const srcPath = path.resolve(cwd(), '..', 'themes-styles', 'src', 'assets', 'assets');
const relativePath = path.relative(dstPath, srcPath);
const relativeFile = path.join(relativePath, 'assets.scss');

function pathValidate(filepath) {
    return filepath && fs.existsSync(filepath)
}

const notValids = [dstPath, dstFilePath, srcPath].filter(p => !pathValidate(p))
if (!notValids || notValids?.length > 0) {
    return;
}

const content = [
    '// index.scss',
    '',
    '// Generated by Command',
    `// Timestamp: ${new Date().toISOString()}`,
    '',
    `@import "${relativeFile}";`,
    ''
].join('\n');

try {
    fs.writeFileSync(dstFilePath, content, 'utf8');
    console.log(`✅ File berhasil disimpan: ${dstFilePath}`);
    return true;
} catch (error) {
    console.error(`❌ Gagal menyimpan file: ${error.message}`);
    return false;
}